
# @name jwt
POST {{SERVER_URL}}/jwt.secret+salt HTTP/1.1
content-type: application/json

{
    "items": [1.1, 2.2, 3.3],
    "foo": {
        "bar": 42
    },
    "user": "me",
    "ttl": 600
}

###

@token = {{jwt.response.body.*}}
GET {{SERVER_URL}}/decode/{{token}} HTTP/1.1
content-type: application/json

###

@token = {{jwt.response.body.*}}
POST {{SERVER_URL}}/decode HTTP/1.1
content-type: text/plain

{{token}}

###

@token = {{jwt.response.body.*}}
POST {{SERVER_URL}}/verify HTTP/1.1
content-type: text/plain

{{token}}
